#!/bin/bash

# Input microseconds since 1900
microseconds_since_1900=$1

# Convert microseconds to seconds
seconds_since_1900=$(echo "$microseconds_since_1900 / 1000000" | bc)

# The difference in seconds between 1900-01-01 and 1970-01-01
diff_seconds=$((2208988800))

# Subtract the difference to get the Unix time (since 1970)
unix_time=$(echo "$seconds_since_1900 - $diff_seconds" | bc)

# Convert to human-readable date
date -d @$unix_time
